# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cores.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cores(object):
    def setupUi(self, Cores):
        Cores.setObjectName("Cores")
        Cores.resize(897, 619)
        self.gridLayout_3 = QtWidgets.QGridLayout(Cores)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(Cores)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.SingleDirectionScrollArea = SingleDirectionScrollArea(self.page)
        self.SingleDirectionScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SingleDirectionScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SingleDirectionScrollArea.setWidgetResizable(True)
        self.SingleDirectionScrollArea.setObjectName("SingleDirectionScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 843, 487))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.SingleDirectionScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.SingleDirectionScrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SingleDirectionScrollArea_2 = SingleDirectionScrollArea(self.page_2)
        self.SingleDirectionScrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SingleDirectionScrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SingleDirectionScrollArea_2.setWidgetResizable(True)
        self.SingleDirectionScrollArea_2.setObjectName("SingleDirectionScrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 82, 16))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.SingleDirectionScrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.SingleDirectionScrollArea_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 3, 0, 1, 6)
        self.BodyLabel = BodyLabel(self.page_3)
        self.BodyLabel.setMaximumSize(QtCore.QSize(42, 33))
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.ComboBox = ComboBox(self.page_3)
        self.ComboBox.setMaximumSize(QtCore.QSize(86, 33))
        self.ComboBox.setObjectName("ComboBox")
        self.gridLayout_2.addWidget(self.ComboBox, 2, 1, 1, 1)
        self.PushButton = PushButton(self.page_3)
        self.PushButton.setMaximumSize(QtCore.QSize(134, 33))
        self.PushButton.setObjectName("PushButton")
        self.gridLayout_2.addWidget(self.PushButton, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        self.SearchLineEdit = SearchLineEdit(self.page_3)
        self.SearchLineEdit.setMaximumSize(QtCore.QSize(491, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.gridLayout_2.addWidget(self.SearchLineEdit, 0, 3, 1, 1)
        self.PushButton_2 = PushButton(self.page_3)
        self.PushButton_2.setMinimumSize(QtCore.QSize(81, 32))
        self.PushButton_2.setMaximumSize(QtCore.QSize(81, 32))
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout_2.addWidget(self.PushButton_2, 0, 5, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 0, 0, 1, 1)

        self.retranslateUi(Cores)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Cores)

    def retranslateUi(self, Cores):
        _translate = QtCore.QCoreApplication.translate
        Cores.setWindowTitle(_translate("Cores", "Frame"))
        self.BodyLabel.setText(_translate("Cores", "过滤："))
        self.ComboBox.setText(_translate("Cores", "正式版"))
        self.PushButton.setText(_translate("Cores", "安装核心"))
        self.PushButton_2.setText(_translate("Cores", "刷新"))
from qfluentwidgets import BodyLabel, ComboBox, PushButton, SearchLineEdit, SingleDirectionScrollArea
