# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(788, 615)
        self.gridLayout_2 = QtWidgets.QGridLayout(home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CardWidget = CardWidget(home)
        self.CardWidget.setMinimumSize(QtCore.QSize(361, 271))
        self.CardWidget.setMaximumSize(QtCore.QSize(361, 271))
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.PixmapLabel = PixmapLabel(self.CardWidget)
        self.PixmapLabel.setStyleSheet("background-color: rgb(80, 217, 255);\n"
"border-radius:3px")
        self.PixmapLabel.setObjectName("PixmapLabel")
        self.gridLayout.addWidget(self.PixmapLabel, 0, 0, 1, 1)
        self.HyperlinkLabel = HyperlinkLabel(self.CardWidget)
        self.HyperlinkLabel.setMaximumSize(QtCore.QSize(343, 28))
        self.HyperlinkLabel.setStyleSheet("HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    font:15pt\n"
"\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}")
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.gridLayout.addWidget(self.HyperlinkLabel, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.CardWidget, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.PrimaryPushButton = PrimaryPushButton(home)
        self.PrimaryPushButton.setMinimumSize(QtCore.QSize(211, 52))
        self.PrimaryPushButton.setCheckable(False)
        self.PrimaryPushButton.setChecked(False)
        self.PrimaryPushButton.setAutoRepeat(False)
        self.PrimaryPushButton.setAutoExclusive(False)
        self.PrimaryPushButton.setProperty("hasIcon", False)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.gridLayout_2.addWidget(self.PrimaryPushButton, 2, 3, 2, 1)
        self.PushButton_2 = PushButton(home)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout_2.addWidget(self.PushButton_2, 2, 0, 1, 2)
        self.HyperlinkButton = HyperlinkButton(home)
        self.HyperlinkButton.setObjectName("HyperlinkButton")
        self.gridLayout_2.addWidget(self.HyperlinkButton, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Frame"))
        self.HyperlinkLabel.setText(_translate("home", "video"))
        self.PrimaryPushButton.setText(_translate("home", "开始练习\n"
"[mc version]"))
        self.PushButton_2.setText(_translate("home", "[type]:[username]"))
        self.HyperlinkButton.setText(_translate("home", "[mc version]"))
from qfluentwidgets import CardWidget, HyperlinkButton, HyperlinkLabel, PixmapLabel, PrimaryPushButton, PushButton
