# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mc_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mc_card(object):
    def setupUi(self, mc_card):
        mc_card.setObjectName("mc_card")
        mc_card.resize(397, 148)
        mc_card.setMinimumSize(QtCore.QSize(397, 0))
        self.gridLayout = QtWidgets.QGridLayout(mc_card)
        self.gridLayout.setObjectName("gridLayout")
        self.CardWidget = CardWidget(mc_card)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PixmapLabel = PixmapLabel(self.CardWidget)
        self.PixmapLabel.setMinimumSize(QtCore.QSize(91, 91))
        self.PixmapLabel.setMaximumSize(QtCore.QSize(91, 91))
        self.PixmapLabel.setStyleSheet("border-image: url(:/solid/solid/Grass.png);")
        self.PixmapLabel.setObjectName("PixmapLabel")
        self.gridLayout_2.addWidget(self.PixmapLabel, 0, 0, 1, 1)
        self.TransparentToolButton = TransparentToolButton(self.CardWidget)
        self.TransparentToolButton.setObjectName("TransparentToolButton")
        self.gridLayout_2.addWidget(self.TransparentToolButton, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.CardWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.StrongBodyLabel = StrongBodyLabel(self.widget)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout_3.addWidget(self.StrongBodyLabel, 0, 0, 1, 1)
        self.BodyLabel = BodyLabel(self.widget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_3.addWidget(self.BodyLabel, 1, 0, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.widget)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_3.addWidget(self.BodyLabel_2, 2, 0, 1, 1)
        self.CaptionLabel = CaptionLabel(self.widget)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.gridLayout_3.addWidget(self.CaptionLabel, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.CardWidget, 0, 0, 1, 1)

        self.retranslateUi(mc_card)
        QtCore.QMetaObject.connectSlotsByName(mc_card)

    def retranslateUi(self, mc_card):
        _translate = QtCore.QCoreApplication.translate
        mc_card.setWindowTitle(_translate("mc_card", "Form"))
        self.StrongBodyLabel.setText(_translate("mc_card", "1.18.2"))
        self.BodyLabel.setText(_translate("mc_card", "正式版"))
        self.BodyLabel_2.setText(_translate("mc_card", "模组加载器:"))
        self.CaptionLabel.setText(_translate("mc_card", "发布日期[date]:"))
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, PixmapLabel, StrongBodyLabel, TransparentToolButton
import icon_rc
